### ISSUE TITLE
Segmentation fault while building

### ISSUE THREAD

**Issue by OliverUv** [laverdet/isolated-vm#98]
Hello! Which compiler(s) and node versions do you use when building and testing? Want to get on the happy path. I recently reinstalled my OS and am having trouble getting my project building/running again. Right now facing some isolated-vm issues.

On node v10.15.1, I could build ok but at runtime node would die during GC because the heap grew too big. After switching to v8.11.2, which I think I was on before the OS reinstall, I'm getting this compilation error during `node rebuild`: https://gist.github.com/7c8408b5bd19c6703d60d85fcb2749a6  (see line 237 for segfault message)

I'm on `uname -srvmpio`: `Linux 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by OliverUv** [comment]
Seems like the out of memory issue is due to other things than isolated-vm, so you can ignore that part. I should note that I could successfully build on node v8.15.0

**Comment by laverdet** [comment]
Oh wow it actually managed to segfault gcc, nice!

I personally use llvm/clang everywhere, 7.0.1 is what I use for development but I know isolated-vm also compiles fine on the 8.0.0 release candidate. I have travis-ci set up to test a matrix of many nodejs versions on Linux and Windows: https://travis-ci.org/laverdet/isolated-vm. It doesn't test across compiler versions because that would explode to a lot of builds very quickly. It tests the gcc-5 Ubuntu package which is the minimum required version of gcc.. right now that is `5.5.0-12ubuntu1~14.04` but I assume the minor version occasionally changes. On Windows it uses the visual studio command line build tools but I don't know which version.

If gcc is crashing the easiest option is going to be to just use a different compiler version. I'd recommend trying the gcc-7 package, or gcc-5 if you want to be sure because that's what is being tested on travis-ci. A compiler segfaulting is a highly unusual problem and is out of my hands for the most part. My experience with these kinds of issues is that you're never the first user to report a compiler error so the issue is likely already known by the team and it's just a matter of waiting for the fix to land in the package manager.

**Comment by OliverUv** [comment]
Haha! score 1-0 between gcc 8.2.0 and isolated-vm.

I'll stick on this version of GCC since it's what comes with this version of Ubuntu. If I have problems in the future I'll probably just go for LLVM instead. Knowing which compiler you focus on is good for when we build the docker build containers for later on. Thanks!

**Comment by laverdet** [comment]
gcc vs llvm is really just a matter of preference. I personally feel that llvm is the better compiler but I think gcc is more popular on Linux systems. I don't think switching to llvm is going to reduce your chances of running into something like this in the future. isolated-vm is built on standard C++14 so theoretically it should work on any compiler that supports that.
