### ISSUE TITLE
4.0.0 regression: "injection reference" pattern no longer works

### ISSUE THREAD

**Issue by isker** [laverdet/isolated-vm#277]
(Apologies for blasting you with so many issues, but they don't necessarily seem like the same problem, at least from my end-user's perspective.)

Here's a pattern we use internally to set up various globals without having to recompile a (not exactly tiny) script every time:

```javascript
const ivm = require("isolated-vm");

// one-time setup
const isolate = new ivm.Isolate();
// pre-compiled script that allows dynamic binding via $INJECTION_REF
const setupScript = isolate.compileScriptSync(`
globalThis.$INJECTION_REF = {};
globalThis.console = {
  log: (...args) => globalThis.$INJECTION_REF.console.getSync('log').applyIgnored(undefined, args)
}
`);
const context = isolate.createContextSync();
setupScript.runSync(context);

// per-request: bind values
const injectionRef = context.global.getSync("$INJECTION_REF");
injectionRef.setSync(
  "console",
  // actual implementation is unique per-request
  { log: (...args) => console.log(...args) },
  { reference: true }
);

// per-request: run request-specific code
context.evalSync('console.log("buh")');

// later: per-request teardown, clear globals, re-use context
```
In 3.3.10, this code works fine and `'buh'` is logged to the console.  In 4.0.0/4.3.6, we get an error: ```TypeError: globalThis.$INJECTION_REF.console.getSync(...).applyIgnored is not a function```.

Strangely enough, changing the definition of `console.log` in the isolate to use promises seems to work in 4.0.0/4.3.6:
```javascript
globalThis.console = {
  log: (...args) => globalThis.$INJECTION_REF.console.get('log').then(log => log.apply(undefined, args))
}
```
But only if you use `apply`; something bad seems to happen if you use `applyIgnored` but there's not a consistent error message.

As a workaround I'm going to stop using this pattern in favor of the working `evalClosureSync` example from https://github.com/laverdet/isolated-vm/issues/276.

**Comment by laverdet** [comment]
`getSync('log')` is now returning a `Callback` instead of a `Reference`. If you change it to `getSync('log', { reference: true })` it will work. The reason you're seeing, what seems to be, the promise version working correctly is that you're actually calling `Function.prototype.apply` and not `Reference.prototype.apply`.

**Comment by isker** [comment]
Aha, that makes sense.  Thanks!

**Comment by isker** [comment]
@laverdet I'm curious if you could explain the mechanics behind this.  It's a bit surprising that `getSync` inside of the isolate returns a `Callback` by default, given that I explicitly set the property on the `injectionRef` as a reference.

How did the reference I set on the outside become a callback on the inside?  I feel like the answer is lurking somewhere around [here](https://github.com/laverdet/isolated-vm/blob/1fef84465c1c2ba44e5d8da3a73f6ef761ae943b/src/module/reference_handle.cc#L488) but I don't see any magic "coerce to Callback" jumping out.

**Comment by isker** [comment]
Ah, and here I am misunderstanding my own test case.  The console object itself was passed as a reference, not the function.  I didn't explicitly do anything about the function.

Still curious where reference properties that are functions get transmuted into Callbacks!
