### ISSUE TITLE
Cannot build on new node 14.11.0 on alpine

### ISSUE THREAD

**Issue by daniel-brenot** [laverdet/isolated-vm#212]
When building on node 14.11.0, the following errors are thrown, which do not show in node version 13.

Docker base image: node:14.11.0-alpine3.10

`> isolated-vm@2.1.0 install /screeps-server/node_modules/isolated-vm
> node-gyp rebuild --release -j 4

make: Entering directory '/screeps-server/node_modules/isolated-vm/build'
  CXX(target) Release/obj.target/nortti/src/external_copy_nortti.o
  AR(target) Release/obj.target/nortti.a
  COPY Release/nortti.a
  CXX(target) Release/obj.target/isolated_vm/src/isolate/allocator.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/class_handle.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/environment.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/executor.o
In file included from ../src/isolate/environment.cc:4:
../src/isolate/platform_delegate.h:222:8: error: 'void ivm::PlatformDelegate::CallOnForegroundThread(v8::Isolate*, v8::Task*)' marked 'final', but is not virtual
   void CallOnForegroundThread(v8::Isolate* isolate, v8::Task* task) final {
        ^~~~~~~~~~~~~~~~~~~~~~
../src/isolate/platform_delegate.h:234:8: error: 'void ivm::PlatformDelegate::CallDelayedOnForegroundThread(v8::Isolate*, v8::Task*, double)' marked 'final', but is not virtual
   void CallDelayedOnForegroundThread(v8::Isolate* isolate, v8::Task* task, double delay_in_seconds) final {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/isolate/platform_delegate.h:262:8: error: 'void ivm::PlatformDelegate::CallIdleOnForegroundThread(v8::Isolate*, v8::IdleTask*)' marked 'final', but is not virtual
   void CallIdleOnForegroundThread(v8::Isolate* isolate, v8::IdleTask* task) final {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/isolate/platform_delegate.h: In member function 'void ivm::PlatformDelegate::CallOnForegroundThread(v8::Isolate*, v8::Task*)':
../src/isolate/platform_delegate.h:230:20: error: 'class v8::Platform' has no member named 'CallOnForegroundThread'; did you mean 'CallOnWorkerThread'?
     node_platform->CallOnForegroundThread(isolate, task);
                    ^~~~~~~~~~~~~~~~~~~~~~
                    CallOnWorkerThread
../src/isolate/platform_delegate.h: In member function 'void ivm::PlatformDelegate::CallDelayedOnForegroundThread(v8::Isolate*, v8::Task*, double)':
../src/isolate/platform_delegate.h:248:20: error: 'class v8::Platform' has no member named 'CallDelayedOnForegroundThread'; did you mean 'CallDelayedOnWorkerThread'?
     node_platform->CallDelayedOnForegroundThread(isolate, task, delay_in_seconds);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    CallDelayedOnWorkerThread
../src/isolate/platform_delegate.h: In member function 'void ivm::PlatformDelegate::CallIdleOnForegroundThread(v8::Isolate*, v8::IdleTask*)':
../src/isolate/platform_delegate.h:263:19: error: 'class v8::Platform' has no member named 'CallIdleOnForegroundThread'; did you mean 'CallOnWorkerThread'?
    node_platform->CallIdleOnForegroundThread(isolate, task);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
                   CallOnWorkerThread
In file included from ../src/isolate/class_handle.h:2,
                 from ../src/isolate/class_handle.cc:1:
/root/.cache/node-gyp/14.11.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = ivm::ClassHandle; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<ivm::ClassHandle>&)]':
../src/isolate/class_handle.h:214:4:   required from 'void ivm::ClassHandle::SetWeak(P*) [with P = ivm::ClassHandle; void (* F)(P*) = ivm::ClassHandle::WeakCallback]'
../src/isolate/class_handle.h:237:55:   required from here
/root/.cache/node-gyp/14.11.0/include/node/v8.h:10867:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<ivm::ClassHandle>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<ivm::ClassHandle>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/isolated_vm/src/isolate/holder.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/inspector.o
  CXX(target) Release/obj.target/isolated_vm/src/isolate/scheduler.o
make: *** [isolated_vm.target.mk:139: Release/obj.target/isolated_vm/src/isolate/environment.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/screeps-server/node_modules/isolated-vm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release" "-j" "4"
gyp ERR! cwd /screeps-server/node_modules/isolated-vm
gyp ERR! node -v v14.11.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! isolated-vm@2.1.0 install: `node-gyp rebuild --release -j 4`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the isolated-vm@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-26T20_32_16_238Z-debug.log`

**Comment by laverdet** [comment]
You're trying to install an old version of isolated-vm. Please update your package.json
